var generic_2dius_2io__context_8h =
[
    [ "dius::IoContext", "classdius_1_1IoContext.html", "classdius_1_1IoContext" ],
    [ "dius::IoContext::OperationStateT&lt; Receiver &gt;::Type", "structdius_1_1IoContext_1_1OperationStateT_1_1Type.html", "structdius_1_1IoContext_1_1OperationStateT_1_1Type" ],
    [ "dius::IoContext::Scheduler::AsyncFile::ReadSomeSender::OperationStateT&lt; Rec &gt;::Type", "structdius_1_1IoContext_1_1Scheduler_1_1AsyncFile_1_1ReadSomeSender_1_1OperationStateT_1_1Type.html", "structdius_1_1IoContext_1_1Scheduler_1_1AsyncFile_1_1ReadSomeSender_1_1OperationStateT_1_1Type" ],
    [ "dius::IoContext::Scheduler::AsyncFile::WriteSomeSender::OperationStateT&lt; Rec &gt;::Type", "structdius_1_1IoContext_1_1Scheduler_1_1AsyncFile_1_1WriteSomeSender_1_1OperationStateT_1_1Type.html", "structdius_1_1IoContext_1_1Scheduler_1_1AsyncFile_1_1WriteSomeSender_1_1OperationStateT_1_1Type" ],
    [ "dius::IoContext::Scheduler::AsyncFile::OpenSender::OperationStateT&lt; Rec &gt;::Type", "structdius_1_1IoContext_1_1Scheduler_1_1AsyncFile_1_1OpenSender_1_1OperationStateT_1_1Type.html", "structdius_1_1IoContext_1_1Scheduler_1_1AsyncFile_1_1OpenSender_1_1OperationStateT_1_1Type" ],
    [ "dius::IoContext::Scheduler::AsyncFile::RunSender::OperationStateT&lt; Rec &gt;::Type", "structdius_1_1IoContext_1_1Scheduler_1_1AsyncFile_1_1RunSender_1_1OperationStateT_1_1Type.html", "structdius_1_1IoContext_1_1Scheduler_1_1AsyncFile_1_1RunSender_1_1OperationStateT_1_1Type" ],
    [ "dius::IoContext::Scheduler::AsyncFile::RunSender::OperationStateT&lt; Rec &gt;::Type::Receiver", "structdius_1_1IoContext_1_1Scheduler_1_1AsyncFile_1_1RunSender_1_1OperationStateT_1_1Type_1_1Receiver.html", "structdius_1_1IoContext_1_1Scheduler_1_1AsyncFile_1_1RunSender_1_1OperationStateT_1_1Type_1_1Receiver" ]
];