#pragma once

#include "di/types/integers.h"
#include "dius/c_definitions.h"

namespace dius::filesystem {
enum class FileType : u32 {
    // These enum values are not generated by posix functions, so pick
    // values which shouldn't overlap the DT_* definitions.
    None = u32(0xffff'ffff),
    NotFound = u32(0xffff'0000),

    Regular = DT_REG,
    Directory = DT_DIR,
    Symlink = DT_LNK,
    Block = DT_BLK,
    Character = DT_CHR,
    Fifo = DT_FIFO,
    Socket = DT_SOCK,
    Unknown = DT_UNKNOWN,
};
}
