#pragma once

#define DIUS_SYSTEM_CALL_INSTRUCTION "svc #0"

#define DIUS_SYSTEM_CALL_ASM_RESULT "x0"
#define DIUS_SYSTEM_CALL_ASM_NUMBER "x8"

#define DIUS_SYSTEM_CALL_ASM_ARG1 "x0"
#define DIUS_SYSTEM_CALL_ASM_ARG2 "x1"
#define DIUS_SYSTEM_CALL_ASM_ARG3 "x2"
#define DIUS_SYSTEM_CALL_ASM_ARG4 "x3"
#define DIUS_SYSTEM_CALL_ASM_ARG5 "x4"
#define DIUS_SYSTEM_CALL_ASM_ARG6 "x5"

#define DIUS_SYSTEM_CALL_CLOBBER "memory"
